export const AI_CONSTANTS = {
  CHUNK_MIN_TOKENS: 300,
  CHUNK_MAX_TOKENS: 800,
  CHUNK_OVERLAP_TOKENS: 50,
  MAX_SEARCH_RESULTS: 10,
  EMBEDDING_BATCH_SIZE: 20,
  SCORE_BOOST: {
    CUSTOMER: 1.3,
    TENANT: 1.1,
    MASTER: 1.0,
  },
  MAX_CONTEXT_TOKENS: 4000,
  MAX_SUMMARY_KEY_POINTS: 7,
} as const;
