export enum ProcessingStatus {
  PENDING = 'PENDING',
  CLEANING = 'CLEANING',
  SUMMARIZING = 'SUMMARIZING',
  DETECTING_INTENTS = 'DETECTING_INTENTS',
  CHUNKING = 'CHUNKING',
  EMBEDDING = 'EMBEDDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
